### PR TITLE
Test IR generation for all PAMELA files

### PR DESCRIPTION
**Pull request by tmarble**
Fixed parser error with between statements.
Added new example coverage.pamela to exercise more language features
  in the process of doing name harmonization.
Changed the test for parser.clj from testing just one IR generation
  to testing all PAMELA files for IR generation.
NOTE: the "rubriques" are checked in to test/pamela/IR/ and
  test/pamela/regression/IR/ but have *not* been hand verified yet.

Signed-off-by: Tom Marble <tmarble@info9.net>

### CODE REVIEW

**Comment by dcerys** [comment]
It looks like the HTN tests assume that each HTN-capable Pamela file has one and only one root task (along with one and only one expected htn.edn file). 
It would be useful to extend the testing framework so that multiple root tasks could be applied to the same Pamela file, one at a time, with different expected TPN and HTN files for each.  Some examples of different root tasks might include:

 * passing different argument lists (with admittedly minor differences in the HTN and TPN).  E.g., different argval types.
 * calling different methods (e.g., “main” and also “submethod1” and “submethod2”).  In some cases, it might be easier to create a large Pamela file with multiple “main”-like methods, each of which uses the same collection of sub methods and supporting pclasses.

A straightforward way to implement this is to include an index as part of the expected HTN and TPN file names.  A single “.root-task” file, or multiple? (either is fine with me)

**Comment by pmdoll** [comment]
I like the idea of a single “.root-task” file and each line in the file represents a "rook task".

**Comment by tmarble** [comment]
Because we are using Instaparse to read the root-task whitespace is considered insignificant.
Rather than somehow making newlines significant in one root-task file I think it would
be cleaner to have indexed root-tasks.... PLAN.0.root-task, PLAN.1.root-task, .... etc.

**Comment by pmdoll** [comment]
Currently, root task is specified via command line option is string and parsed? by instaparse.  We could always read the line from the file and hand it off to instaparse just as we do now.

For now, since there is only a single root task, there will be 1:1 relation between root tasks and file. But as we add more tasks the number of root task files will increase. Should it become unmanageable, we could always adopt multiple root tasks per file.

**Comment by tmarble** [comment]
@pmdoll yes root-task is parsed by Instaparse from the command line string.

Are you saying you do NOT want indexed root-task files AND (instead) want to read root-task(s)
from a PLAN.root-task file where each newline is significant? 

If that is the case can you suggest a naming convention for the expected output .htn.edn and .tpn.edn files?

If that is NOT the case are you OK with the indexed approach?

**Comment by pmdoll** [comment]
I am ok with the indexed approach.

**Comment by dcerys** [comment]
To clarify things (I hope), let’s say we have a Pamela file named `hairy-stuff.pamela`.  If we had a single applicable root task, we might call the file containing that root task (simply) `hairy-stuff.root-task` or `hairy-stuff.<disambiguator>.root-task`.  The current proposal assumes the `<disambiguator>` is a 0-based index, but couldn’t it actually be any non-dot-containing string, with possibly some semantic meaning?  E.g., `hairy-stuff.1.root-task` or `hairy-stuff.subtask1.root-task`

**Comment by tmarble** [comment]
@dcerys I was thinking a number, but there's no reason it couldn't be a generic disambiguator.

**Comment by tmarble** [comment]
Just added this "multiple root-tasks feature" in 4bd1ba7

**Pull request merged**
