### PR TITLE
Fix using default bounds for TPN's generated with HTN method

### LINKED ISSUE #98: HTN/TPN generation doesn't include bounds (or other metadata) declared for primitive methods
In the following example, the `:bounds` declared for the primitive methods (e.g., `do-a`) aren't included in the generated TPN (generated using the `htn` action)

```
(defpclass plant []
           :meta {:doc "The Plant API"}
           :methods [(defpmethod do-a {:bounds [2 4]} [])
                     (defpmethod do-b {:bounds [3 6]} [])
                     (defpmethod do-c {:bounds [4 8]} [])
                     (defpmethod do-d [])                  
                     (defpmethod do-e {:bounds [5 10]} [])])

(defpclass infeasible-sequence [plnt]
           :meta {:doc "An example of infeasible sequence of activties"}
           :methods [(defpmethod start
                                 {:doc "Simple TPN with constraints"}
                                 []
                                 (sequence :bounds [10 30]
                                           (plnt.do-a)
                                           (plnt.do-b)
                                           (plnt.do-c)
                                           (plnt.do-d)
                                           (plnt.do-e)))])
```

### LINKED ISSUE #108: Missing constraints in activities
Commit ff326131edcb79004386c6459308c7d303f9141e has relevant artifacts.

I expect `tpn` file as in this commit. 
@dcerys Please verify and update `htn` file.
@tmarble Please verify both `htn and tpn` files.

### PR DESCRIPTION
**Pull request by tmarble**
Consistently throw exceptions in HTN generation using fatal-error
Closes #98
Closes #108

Signed-off-by: Tom Marble <tmarble@info9.net>

### CODE REVIEW

**Comment by pmdoll** [comment]
In test/pamela/HTN/coverage.main.tpn.edn, line 225 changed from
`#{:costle-87 :tc-86 :rewardge-88}`  to `#{:rewardge-89 :costle-88 :tc-87}` . What caused the sort order to change? For consistency, I think edn should be sorted just before writing to the file. Is it not the case?

**Comment by tmarble** [comment]
Clearly the UID's are offset by one as there was probably a new constraint which was created since the previous rubric.

The EDN *is* sorted insomuch as the keys of maps are in order. However the values are *not* sorted. In particular sets do not have an order. If we start to have failures due simply to this class of problems we can re-examine the merits of doing literal file contents comparison.

**Comment by pmdoll** [comment]
Motivation behind literal file content comparison is to ensure and verify that code changes do not inadvertently introduce an unexpected change in produced artifacts which could have ripple effects.

For this PR, I do expect minor changes in UIDs but was wondering what caused the set values to be printed in different order than before. So it seems like it is definitely a change in code that caused the insertion order to be different.

**Comment by dcerys** [comment]
As mentioned above, sets, by default are unsorted.  If the order was consistent beforehand, we were just lucky.  Although we **could** address this by using `sorted-set` in cases like this, that seems like a slippery slope of code obfuscation.  If necessary, I'd rather have the equivalence checker do the work.

**Comment by tmarble** [comment]
For reference:
```clojure
pamela.cli> (= {:a 123 :b #{:third :first :second}} {:b #{:first :second :third} :a 123})
true
pamela.cli> (= "{:a 123 :b #{:third :first :second}}" "{:b #{:first :second :third} :a 123}")
false
pamela.cli> 
```
Our current checks are equivalent to the second kind of comparison.

**Comment by dcerys** [comment]
Since it doesn't fully close #98, I'll reopen it after closing this PR

**Pull request merged**
