### PR TITLE
Issue 102

### PR DESCRIPTION
**Pull request by tmarble**

### CODE REVIEW

**Comment by tmarble** [comment]
@pmdoll _BEFORE_ you merge this PR please:

1. NOTE: that one test fails because it will require updating plan-schema coercion (which should be done separately). see details below...
2. Please test this (you can checkout tmarble/issue-102) on your betweens example(s) (e.g. first.pamela)
3. Please test this to confirm that the :end-nodes are as you like them per #105 


```
HTN and TPN Json coercion
"files differ" "target/gen-files/isr-htn.tpn.edn.clj" "target/gen-files/isr-htn.tpn.json.clj" " See diff for details"

expected: "target/gen-files/isr-htn.tpn.edn.clj"
  actual: "target/gen-files/isr-htn.tpn.json.clj"
    diff: - "target/gen-files/isr-htn.tpn.edn.clj"
          + "target/gen-files/isr-htn.tpn.json.clj"
--- target/gen-files/isr-htn.tpn.edn.clj	2017-05-10 16:49:46.088940602 -0500
+++ target/gen-files/isr-htn.tpn.json.clj	2017-05-10 16:49:46.640945076 -0500
@@ -591,7 +591,7 @@
   :activities #{:act-9},
   :incidence-set #{},
   :htn-node :hem-40,
-  :sequence-end :node-4},
+  :sequence-end "node-4"},
```

**Comment by dcerys** [comment]
Planviz will also need to be updated, since it will now complain about missing `:label` keys in the TPN.

**Comment by tmarble** [comment]
@dcerys I will add those comments.

I'm also working on a corresponding update to **plan-schema** which includes several coercion fixes (which will result in new rubrics).

**Comment by pmdoll** [comment]
There are 3 top-level blocks in Pamela for which we need **end-node** slot, namely *parallel*, *choice* and *sequence*. For *parallel* and *choice*, we do have **end-node** slot. i.e We add this slot to corresponding begin nodes (p-begin and c-begin). 

For sequences that do not have a parallel or choice as their first element, we use *state* node as begin node. It is only for this **state** node and not any other state node, we need to add **end-slot**. i.e If the **first** node of the sequence is a state node, then only it will have end-node and not otherwise.

Consider the example from 

```
regression/HTN/sequence-bounds.example.tpn.edn
This is the first node of the sequence and it must have `:end-node :node-1`. Currently, it does not. So there is another bug waiting to be squashed somewhere.
:node-7
             {:tpn-type      :state,
              :uid           :node-7,
              :constraints   #{:tc-4},
              :activities    #{:da-6},
              :incidence-set #{},
              :htn-node      :hem-14},
```

**Comment by dcerys** [comment]
When applying the `'htn` action, the TPN generated now includes a large number of null activities that weren't present before.  Here's the planviz view using test/pamela/quadcopter.pamela.  The tooltip confirms that the edges without labels are null activities.

screenshot 2017-05-15 15 58 17

**Comment by dcerys** [comment]
There's a minor problem with arg-generation (see quadcopter.waypoints.htn.edn), but I'll address that with a separate PR

**Pull request merged**
